server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9196
