server:
  port: 9192
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9196
logging:
  file: C:/Users/richshar/Desktop/gitLab/ZipkinDemo/logfile/zipkinProject.log